### ISSUE TITLE
加载蒙版图片的时候出错

### ISSUE THREAD

**Issue by PhilChina** [parksben/barrage#2]
### 这是我写的demo
![image](https://user-images.githubusercontent.com/24240989/56021790-e43af200-5d3c-11e9-8a57-ef8e3939f4f2.png)
### 但是浏览器中报错如上，不知道是哪里的问题。我看了Barrage UI 的源码，但是我刚接触这些东西，没有找到问题所在
![image](https://user-images.githubusercontent.com/24240989/56021885-1d736200-5d3d-11e9-8460-13e3d1d3d585.png)

**Comment by parksben** [comment]
【问题定位】使用者理解有偏差，非项目特性问题，已线下联系解决。
