### ISSUE TITLE
无法在vue里面使用，是否不支持呢？ 

### ISSUE THREAD

**Issue by fengxiaolei** [parksben/barrage#5]
![image](https://user-images.githubusercontent.com/8679403/59812407-70baef80-9340-11e9-902e-09abb7266e46.png)
请看截图，按照demo在实例化的时候，报错

**Comment by parksben** [comment]
请给出具体的代码片段帮助定位问题，或者微信联系我共同讨论：Xreaman

**Comment by fengxiaolei** [comment]
目前已更换其它方法临时处理，过后在跟进， 谢谢！

**Comment by parksben** [comment]
那我先暂时关掉这个issue吧
推荐你使用 最新版本 1.3.2

之前有几个童鞋都提过类似问题
都是业务理解或者对 react、vue 框架理解欠妥的原因
与 barrage-ui 的能力并无大的关系

如果后续有什么建议，欢迎提issue或者PR，谢~
